### ISSUE TITLE
can't disable oregen in 1.19.2

### ISSUE THREAD

**Issue by coco875** [igentuman/NuclearCraft-Neoteric#34]
I try disable oregen with this config:
```toml
#Settings for ore generation
[ores]
	#List of dimensions to generate ores: lithium, platinum, thorium, tin, magnesium, silver, cobalt, uranium, zinc, boron, lead
	dimensions = [[0, -4848], [0, -4848], [0, -4848], [0, -4848], [0, -4848], [0, -4848], [0, -4848], [0, -4848], [0, -4848], [0, -4848], [0, -4848]]
	#Enable ore registration: lithium, platinum, thorium, tin, magnesium, silver, cobalt, uranium, zinc, boron, lead
	register_ore = []
	#Ore blocks per vein. Order: lithium, platinum, thorium, tin, magnesium, silver, cobalt, uranium, zinc, boron, lead
	vein_size = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	#Veins in chunk. Order: lithium, platinum, thorium, tin, magnesium, silver, cobalt, uranium, zinc, boron, lead
	veins_in_chunk = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	#Minimal generation height. Order: lithium, platinum, thorium, tin, magnesium, silver, cobalt, uranium, zinc, boron, lead
	min_height = [-60, -60, -60, 4, -60, -60, -60, -60, 4, -60, 4]
	#Max generation height. Order: lithium, platinum, thorium, tin, magnesium, silver, cobalt, uranium, zinc, boron, lead
	max_height = [60, 0, 60, 60, 60, 60, 60, 60, 60, 60, 60]
```
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/59367621/54801694-de34-44fe-a30c-250f6d257d27)
but don't work
